"""TaskSTatus

Revision ID: 0f0ba774116f
Revises: 93424be1551a
Create Date: 2025-06-18 12:14:23.275602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0ba774116f'
down_revision: Union[str, None] = '93424be1551a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_name', 'status', name='unique_active_task')
    )
    op.create_index(op.f('ix_task_status_task_id'), 'task_status', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_status_task_name'), 'task_status', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_status_user_id'), 'task_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_user_id'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_task_name'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_task_id'), table_name='task_status')
    op.drop_table('task_status')
    # ### end Alembic commands ###
