"""add is_active to subscription

Revision ID: 707b18bffbcf
Revises: 6a3aabe0ed32
Create Date: 2025-04-25 09:44:41.786916+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707b18bffbcf'
down_revision: Union[str, None] = '6a3aabe0ed32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###
