"""Employee Inviate

Revision ID: 93424be1551a
Revises: 283598832fd1
Create Date: 2025-05-29 17:23:46.821358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93424be1551a'
down_revision: Union[str, None] = '283598832fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_invites_token'), 'employee_invites', ['token'], unique=True)
    op.add_column('employees', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=False)
    op.drop_column('employees', 'full_name')
    op.drop_index('ix_wb_stocks_days_import_date', table_name='wb_stocks')
    op.drop_index('ix_wb_stocks_days_last_сhange_date', table_name='wb_stocks')
    op.drop_index('ix_wb_stocks_days_nm_id', table_name='wb_stocks')
    op.drop_index('ix_wb_stocks_days_supplier_article', table_name='wb_stocks')
    op.drop_index('ix_wb_stocks_days_user_id', table_name='wb_stocks')
    op.create_index(op.f('ix_wb_stocks_import_date'), 'wb_stocks', ['import_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_last_сhange_date'), 'wb_stocks', ['last_сhange_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_nm_id'), 'wb_stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_supplier_article'), 'wb_stocks', ['supplier_article'], unique=False)
    op.create_index(op.f('ix_wb_stocks_user_id'), 'wb_stocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_stocks_user_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_supplier_article'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_nm_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_last_сhange_date'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_import_date'), table_name='wb_stocks')
    op.create_index('ix_wb_stocks_days_user_id', 'wb_stocks', ['user_id'], unique=False)
    op.create_index('ix_wb_stocks_days_supplier_article', 'wb_stocks', ['supplier_article'], unique=False)
    op.create_index('ix_wb_stocks_days_nm_id', 'wb_stocks', ['nm_id'], unique=False)
    op.create_index('ix_wb_stocks_days_last_сhange_date', 'wb_stocks', ['last_сhange_date'], unique=False)
    op.create_index('ix_wb_stocks_days_import_date', 'wb_stocks', ['import_date'], unique=False)
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_column('employees', 'username')
    op.drop_index(op.f('ix_employee_invites_token'), table_name='employee_invites')
    op.drop_table('employee_invites')
    # ### end Alembic commands ###
