"""fix_unique_task_status

Revision ID: a6e7e2d04e92
Revises: 0f0ba774116f
Create Date: 2025-06-18 14:47:25.686327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e7e2d04e92'
down_revision: Union[str, None] = '0f0ba774116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_active_task', 'task_status', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_active_task', 'task_status', ['user_id', 'task_name', 'status'])
    # ### end Alembic commands ###
