"""add wb models

Revision ID: 283598832fd1
Revises: 707b18bffbcf
Create Date: 2025-04-27 09:34:12.235026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283598832fd1'
down_revision: Union[str, None] = '707b18bffbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_change_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_article', sa.String(length=75), nullable=False),
    sa.Column('tech_size', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('finished_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('spp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('warehouse_name', sa.String(length=50), nullable=False),
    sa.Column('region_name', sa.String(length=200), nullable=False),
    sa.Column('oblast_okrug_name', sa.String(length=200), nullable=True),
    sa.Column('country_name', sa.String(length=200), nullable=True),
    sa.Column('income_id', sa.BigInteger(), nullable=True),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('is_cancel', sa.Boolean(), nullable=False),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('g_number', sa.String(length=60), nullable=False),
    sa.Column('sticker', sa.String(length=255), nullable=False),
    sa.Column('srid', sa.String(length=255), nullable=True),
    sa.Column('price_with_disc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=True, comment='Договор поставки'),
    sa.Column('is_realization', sa.Boolean(), nullable=True, comment='Договор реализации'),
    sa.Column('warehouse_type', sa.String(length=60), nullable=True, comment='Тип склада'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', 'srid', 'nm_id', 'is_cancel', 'tech_size', name='unique_order')
    )
    op.create_index(op.f('ix_wb_orders_date'), 'wb_orders', ['date'], unique=False)
    op.create_index(op.f('ix_wb_orders_last_change_date'), 'wb_orders', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_wb_orders_nm_id'), 'wb_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_orders_user_id'), 'wb_orders', ['user_id'], unique=False)
    op.create_table('wb_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_change_date', sa.DateTime(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('oblast_okrug_name', sa.String(length=255), nullable=True),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('tech_size', sa.String(length=50), nullable=False),
    sa.Column('income_id', sa.BigInteger(), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=False),
    sa.Column('is_realization', sa.Boolean(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('spp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('for_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('finished_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_with_disc', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_sale_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sale_id', sa.String(length=255), nullable=True),
    sa.Column('sticker', sa.String(length=255), nullable=False),
    sa.Column('g_number', sa.String(length=255), nullable=False),
    sa.Column('srid', sa.String(length=255), nullable=True),
    sa.Column('warehouse_type', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', 'srid', 'nm_id', 'tech_size', name='unique_sale')
    )
    op.create_index(op.f('ix_wb_sales_date'), 'wb_sales', ['date'], unique=False)
    op.create_index(op.f('ix_wb_sales_last_change_date'), 'wb_sales', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_wb_sales_nm_id'), 'wb_sales', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_srid'), 'wb_sales', ['srid'], unique=False)
    op.create_index(op.f('ix_wb_sales_supplier_article'), 'wb_sales', ['supplier_article'], unique=False)
    op.create_index(op.f('ix_wb_sales_user_id'), 'wb_sales', ['user_id'], unique=False)
    op.create_table('wb_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('last_сhange_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_article', sa.String(length=75), nullable=False),
    sa.Column('tech_size', sa.String(length=30), nullable=True),
    sa.Column('barcode', sa.String(length=30), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_full', sa.Integer(), nullable=False),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.Column('is_realization', sa.Boolean(), nullable=True),
    sa.Column('in_way_to_client', sa.Integer(), nullable=False),
    sa.Column('in_way_from_client', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=50), nullable=False),
    sa.Column('sc_code', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_date', 'user_id', 'warehouse_name', 'nm_id', name='unique_stocks')
    )
    op.create_index(op.f('ix_wb_stocks_days_import_date'), 'wb_stocks', ['import_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_days_last_сhange_date'), 'wb_stocks', ['last_сhange_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_days_nm_id'), 'wb_stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_days_supplier_article'), 'wb_stocks', ['supplier_article'], unique=False)
    op.create_index(op.f('ix_wb_stocks_days_user_id'), 'wb_stocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_stocks_user_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_supplier_article'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_nm_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_last_сhange_date'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_import_date'), table_name='wb_stocks')
    op.drop_table('wb_stocks')
    op.drop_index(op.f('ix_wb_sales_user_id'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_supplier_article'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_srid'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_nm_id'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_last_change_date'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_date'), table_name='wb_sales')
    op.drop_table('wb_sales')
    op.drop_index(op.f('ix_wb_orders_user_id'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_nm_id'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_last_change_date'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_date'), table_name='wb_orders')
    op.drop_table('wb_orders')
    # ### end Alembic commands ###
