"""upgrade stocks

Revision ID: 427ba5e59de5
Revises: a6e7e2d04e92
Create Date: 2025-06-19 11:40:47.127220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '427ba5e59de5'
down_revision: Union[str, None] = 'a6e7e2d04e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_stocks', sa.Column('last_change_date', sa.DateTime(), nullable=False))
    op.drop_index('ix_wb_stocks_import_date', table_name='wb_stocks')
    op.drop_index('ix_wb_stocks_last_сhange_date', table_name='wb_stocks')
    op.drop_constraint('unique_stocks', 'wb_stocks', type_='unique')
    op.create_unique_constraint('unique_stocks', 'wb_stocks', ['user_id', 'warehouse_name', 'nm_id'])
    op.create_index(op.f('ix_wb_stocks_last_change_date'), 'wb_stocks', ['last_change_date'], unique=False)
    op.drop_column('wb_stocks', 'last_сhange_date')
    op.drop_column('wb_stocks', 'import_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_stocks', sa.Column('import_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('wb_stocks', sa.Column('last_сhange_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wb_stocks_last_change_date'), table_name='wb_stocks')
    op.drop_constraint('unique_stocks', 'wb_stocks', type_='unique')
    op.create_unique_constraint('unique_stocks', 'wb_stocks', ['import_date', 'user_id', 'warehouse_name', 'nm_id'])
    op.create_index('ix_wb_stocks_last_сhange_date', 'wb_stocks', ['last_сhange_date'], unique=False)
    op.create_index('ix_wb_stocks_import_date', 'wb_stocks', ['import_date'], unique=False)
    op.drop_column('wb_stocks', 'last_change_date')
    # ### end Alembic commands ###
